config/routes.rb
Rails.application.routes.draw do
  root "users#show"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :account_activations, only: [:edit]
  resources :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  has_many :tastes, dependent: :destroy, inverse_of: :item
  has_many :areas, dependent: :destroy, inverse_of: :item
  accepts_nested_attributes_for :tastes, allow_destroy: true
  accepts_nested_attributes_for :areas, allow_destroy: true

  validates :name, presence: true, length: { maximum: 50 }
  validates :bitterness, presence:true, 
            numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :acidity, presence:true, 
            numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :body, presence:true, 
            numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :variety, length: { maximum: 50 }
  validates :process, length: { maximum: 50 }
  validates :farm, length: { maximum: 50 }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = current_user
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = "New item created"
      redirect_to root_path
    else
      flash[:danger] = "Create new item failed"
      redirect_to root_path
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    ActiveRecord::Base.transaction do
      if @item.update!(item_params)
        if item_params.has_key?(:tastes_attributes)
          item_params[:tastes_attributes].each do |taste_hash|
            if (!taste_hash[1].has_key?(:taste)) && taste_hash[1].has_key?(:id)
              Taste.find(taste_hash[1][:id]).destroy!
            end
          end
        end

        if item_params.has_key?(:areas_attributes)
          item_params[:areas_attributes].each do |area_hash|
            if (!area_hash[1].has_key?(:area)) && area_hash[1].has_key?(:id)
              Area.find(area_hash[1][:id]).destroy!
            end
          end
        end

        flash[:success] = "Item updated"
        redirect_to @item
      else
        flash[:danger] = "Item update failed"
        redirect_to @item
      end
    end
  rescue
    flash[:danger] = "Item update failed"
    redirect_to @item
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:success] = "Item deleted"
    redirect_to root_path
  end

  private
    # 正しいユーザでなければリダイレクト
    def correct_user
      @item = Item.find(params[:id])
      @user = User.find(@item.user_id)
      if @user != current_user
        flash[:danger] = "Invalid item id"
        redirect_to(root_url, status: :see_other)
      end
    end

    def item_params
      params.require(:item).permit(:name, :bitterness, :acidity, :body, :roast, :variety, :process, :farm, :shop_url, :description,
                                    tastes_attributes: [:taste, :id], areas_attributes: [:area, :id])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<%= link_to(item_path(item)) do %>
  <div class="col-md-3 col-xs-12">
    <div class="panel">
      <div class="title"><%= item.name %></div>
      <div class="item_prop">
        <div>Bitterness</div>
        <input type="range" min=1 max=5 value=<%= item.bitterness%> readonly />
      </div>
      <div class="item_prop">
        <div>Acidity</div>
        <input type="range" min=1 max=5 value=<%= item.acidity%> readonly />
      </div>
      <div class="item_prop">
        <div>Body</div>
        <input type="range" min=1 max=5 value=<%= item.body%> readonly />
      </div>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<% provide(:title, "edit item") %>

<div class="title_container">
  <h1>Update item</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @item) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :bitterness %>
      <%= f.range_field :bitterness, in: 1..5, class: 'form-control' %>

      <%= f.label :acidity %>
      <%= f.range_field :acidity, in: 1..5, class: 'form-control' %>

      <%= f.label :body %>
      <%= f.range_field :body, in: 1..5, class: 'form-control' %>

      <%= f.label :tastes %>
      <div id="taste_form_container">
        <%= f.fields_for :tastes do | taste | %>
          <%= taste.text_field :taste, data: {index: taste.index}, class: "taste_form"  %>
        <% end %>
      </div>
      <div class="button_container">
        <button id="add_taste" type="button">add</button>
        <button id="reduce_taste" type="button">reduce</button>
      </div>

      <%= f.label :areas %>
      <div id="area_form_container">
        <%= f.fields_for :areas do | area | %>
          <%= area.text_field :area, data: {index: area.index}, class: "area_form" %>
        <% end %>
      </div>
      <div class="button_container">
        <button id="add_area" type="button">add</button>
        <button id="reduce_area" type="button">reduce</button>
      </div>

      <%= f.label :roast %>
      <%= f.text_field :roast, class: 'form-control' %>

      <%= f.label :variety %>
      <%= f.text_field :variety, class: 'form-control' %>

      <%= f.label :process %>
      <%= f.text_field :process, class: 'form-control' %>

      <%= f.label :farm %>
      <%= f.text_field :farm, class: 'form-control' %>

      <%= f.label :shop_url, "Shop URL" %>
      <%= f.url_field :shop_url, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<% provide(:title, "new item") %>
<div class="title_container">
  <h1>New item</h1>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @item) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :bitterness %>
      <%= f.range_field :bitterness, in: 1..5, class: 'form-control' %>

      <%= f.label :acidity %>
      <%= f.range_field :acidity, in: 1..5, class: 'form-control' %>

      <%= f.label :body %>
      <%= f.range_field :body, in: 1..5, class: 'form-control' %>

      <%= f.label :tastes %>
      <div id="taste_form_container">
        <%= f.fields_for :tastes do | taste | %>
          <%= taste.text_field :taste, data: {index: taste.index}, class: "taste_form"  %>
        <% end %>
      </div>
      <div class="button_container">
        <button id="add_taste" type="button">add</button>
        <button id="reduce_taste" type="button">reduce</button>
      </div>

      <%= f.label :areas %>
      <div id="area_form_container">
        <%= f.fields_for :areas do | area | %>
          <%= area.text_field :area, data: {index: area.index}, class: "area_form" %>
        <% end %>
      </div>
      <div class="button_container">
        <button id="add_area" type="button">add</button>
        <button id="reduce_area" type="button">reduce</button>
      </div>

      <%= f.label :roast %>
      <%= f.text_field :roast, class: 'form-control' %>

      <%= f.label :variety %>
      <%= f.text_field :variety, class: 'form-control' %>

      <%= f.label :process %>
      <%= f.text_field :process, class: 'form-control' %>

      <%= f.label :farm %>
      <%= f.text_field :farm, class: 'form-control' %>

      <%= f.label :shop_url, "Shop URL" %>
      <%= f.url_field :shop_url, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<% provide(:title, "detail") %>
<div class="title_container">
  <h1><%= @item.name %></h1>
  <% if !@item.shop_url.empty? %>
    <a href=<%= @item.shop_url%>><%= @item.shop_url%></a>
  <% end %>
</div>
<div class="item_detail">
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <div class="item_prop">
        <div class="prop_name">Bitterness</div>
        <input type="range" min=1 max=5 value=<%= @item.bitterness%> readonly/>
      </div>
      <div class="item_prop">
        <div class="prop_name">Acidity</div>
        <input type="range" min=1 max=5 value=<%= @item.acidity%> readonly/>
      </div>
      <div class="item_prop">
        <div class="prop_name">Body</div>
        <input type="range" min=1 max=5 value=<%= @item.body%> readonly/>
      </div>
      <div class="tastes">
        <% if @item.tastes.any? %>
          <%  @item.tastes.each do |taste| %>
            <span><%= taste.taste %></span>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="item_prop">
        <% if @item.areas.any? %>
          <div class="prop_name">Area</div>
          <div>
            <% @item.areas.each_with_index do |area, i| %>
              <% if i != 0 %>,<% end %>
              <%= area.area %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="item_prop">
        <div class="prop_name">Roast</div>
        <div><%= @item.roast %></div>
      </div>
      <div class="item_prop">
        <div class="prop_name">Variety</div>
        <div><%= @item.variety %></div>
      </div>
      <div class="item_prop">
        <div class="prop_name">Process</div>
        <div><%= @item.process %></div>
      </div>
      <div class="item_prop">
        <div class="prop_name">Farm</div>
        <div><%= @item.farm %></div>
      </div>
    </div>
    <div class="col-md-12 item_description">
      <%= @item.description %>
    </div>
  </div>
  <div class="button_container">
    <%= link_to "Delete", @item, class: "btn btn-danger",
      data: { turbo_method: :delete, turbo_confirm: "You sure?" } %>
    <%= link_to "Edit", edit_item_path(@item), class: "btn btn-primary" %>
  </div>
</div>